name: pack to nuget

on:
  push:
    tags:
      - "vRelease*"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: get sources
      uses: actions/checkout@v3

    - name: Set up .NET Core 6
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.x'
        include-prerelease: false

    - name: Set up .NET Core 7
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
        include-prerelease: false

    - name: Build with dotnet
      run: |
        cd src
        cd SkinnyControllers
        dotnet tool restore
        dotnet r packV2
        dotnet r packCommon

    - name: push to nuget
      run: |
          dotnet nuget push ${{github.workspace}}/src/SkinnyControllers/PACK/*symb*.*pkg --api-key  ${{ secrets.NUGETAPIKEY }} --source https://api.nuget.org/v3/index.json

